
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: phucdev
  password: 123456

development:
  <<: *default
  database: funny_movie_development

  
test:
  <<: *default
  database: funny_movie_test


production:
  <<: *default
  database: funny_movie_production
  username: funny_movie
  password: <%= ENV["FUNNY_MOVIE_DATABASE_PASSWORD"] %>
